<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1dfce20baf48f7a104bb3ce097d3d9b9
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'Codehaveli\\Wbitly\\' => 18,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Codehaveli\\Wbitly\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1dfce20baf48f7a104bb3ce097d3d9b9::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1dfce20baf48f7a104bb3ce097d3d9b9::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit1dfce20baf48f7a104bb3ce097d3d9b9::$classMap;

        }, null, ClassLoader::class);
    }
}
