name: Update WordPress.org Readme

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-readme:
    name: Update WordPress.org Readme
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update WordPress.org readme
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: codehaveli-bitly-url-shortener
          README_NAME: readme.txt
          IGNORE_OTHER_FILES: true
          SKIP_ASSETS: true
